### ISSUE TITLE
describle-function and describe-variables no longer use ido in emacs 25

### ISSUE THREAD

**Issue by sollidsnake** [DarwinAwardWinner/ido-ubiquitous#110]
When using emacs 25 -- `25.1.50.1` to be more precise --, emacs falls back to the default completion method when invoking `describe-function` or `describle-variable`. For most other commands, like `set-variable` and non-builtin, ido completion keep working just fine.

**Comment by DarwinAwardWinner** [comment]
These functions were modified in 25.1, and I had to make some fixes in ido-ubiquitous for them to work. This should be fixed in version 3.14

**Comment by dgutov** [comment]
Note that in doing so, you're breaking the new feature: automatic loading of packages based on known variable/function name prefixes.

**Comment by DarwinAwardWinner** [comment]
So if I understand correctly from a quick look at the code, the new feature allows commands like `describe-function` to automatically load elisp files that are known to define functions that match a prefix entered by the user, in order to offer a more accurate set of completions, based on some pre-processing that builds a mapping from prefixes to filenames?

**Comment by dgutov** [comment]
Yes.

**Comment by cpitclaudel** [comment]
@DarwinAwardWinner Support for this new feature in `ido` would be brilliant.

**Comment by DarwinAwardWinner** [comment]
Ok, I guess in the short term I'll just have to remove the override, and people who value ido completion more than this new feature can add it back themselves. I'll open a new issue for investigating whether ido completion can support this feature. Thanks for bringing this to my attention.

**Comment by j-cr** [comment]
So how do I enable it? 20200520.1535, Emacs 26
